stages:
  - trigger
  - publish


trigger-veracode-scan:
  # prepare and submit for static code analysis
  stage: trigger
  only:
    variables:
      - $VERACODE_API_ID
  image: advancedtelematic/gitlab-jobs:0.1.0
  before_script:
    # The latest wrapper version can be found in https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/
    - wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/${VERACODE_WRAPPER_VERSION}/vosp-api-wrappers-java-${VERACODE_WRAPPER_VERSION}.jar
    - ./sbt package
    - mv target/scala-*/treehub_*.jar ./scan.jar
  script:
    - java -jar veracode-wrapper.jar -vid ${VERACODE_API_ID} -vkey ${VERACODE_API_KEY}
      -action UploadAndScan -appname "OTA Backend - treehub" -createprofile true -autoscan true
      -filepath scan.jar -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID} for ${CI_PROJECT_NAME} repo"
  artifacts:
    paths:
      - scan.jar

trigger-deps-scan:
  # perform dependencies CVE analysis
  stage: trigger
  only:
    - schedules
  image: advancedtelematic/gitlab-jobs:0.1.0
  script:
    - ./sbt dependencyCheckAggregate
    - mv target/scala-*/dependency-check-report.html ./depchk.html
  artifacts:
    paths:
      - depchk.html

pages:
  stage: publish
  only:
    - schedules
  dependencies:
    - trigger-deps-scan
  script:
    - mkdir -p public
    - mv depchk.html public/index.html
  artifacts:
    paths:
      - public
    expire_in: 64 days
