/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_advancedtelematic_libostree_LibOstree */

#ifndef _Included_com_advancedtelematic_libostree_LibOstree
#define _Included_com_advancedtelematic_libostree_LibOstree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_advancedtelematic_libostree_LibOstree
 * Method:    parentOf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_advancedtelematic_libostree_LibOstree_parentOf
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
