ALTER TABLE object
ADD updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE object
ADD created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE ref
ADD updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE ref
ADD created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
;
